export const adminOperations = [
  'health',
  'dashboard.today',
  'dashboard.v15',
  'dashboard.analytics',
  'deliverySlots.list',
  'deliverySlots.create',
  'deliverySlots.update',
  'deliverySlots.setActive',
  'deliveryDays.get',
  'deliveryDays.setOverride',
  'foodCategories.list',
  'foodCategories.create',
  'foodCategories.update',
  'foodTags.list',
  'foodTags.create',
  'foodTags.update',
  // Reference data and checkout configuration are listed per entity rather than through one
  // aggregate read. The aggregate forced every screen that needed a single list — the tag editor,
  // the manual-order form — to be granted the whole set, including payment terms.
  'foodTagGroups.list',
  'foodTagGroups.create',
  'foodTagGroups.update',
  'supportSubjects.list',
  'supportSubjects.create',
  'supportSubjects.update',
  'paymentMethods.list',
  'paymentMethods.update',
  'deliveryMethods.list',
  'deliveryMethods.update',
  'foods.list',
  'foods.create',
  'foods.update',
  'foods.setActive',
  'menus.get',
  'menus.settings',
  'menus.addItem',
  'menus.updateItem',
  'menus.removeItem',
  'customers.lookup',
  'orders.search',
  'orders.get',
  'orders.create',
  'orders.updateStatus',
  'support.conversations.list',
  'support.conversations.get',
  'support.conversations.reply',
  'support.conversations.setClosed',
  'support.reviews.list',
  'support.reviews.setStatus',
  'support.reviews.reply',
  'units.list',
  'units.save',
  'ingredients.list',
  'ingredients.create',
  'ingredients.update',
  'suppliers.list',
  'suppliers.create',
  'suppliers.update',
  'purchases.list',
  'purchases.create',
  'purchases.confirm',
  'purchases.cancel',
  'purchases.pay',
  'inventory.movements',
  'inventory.adjust',
  'inventory.waste',
  'inventory.count',
  'recipes.get',
  'recipes.save',
  'finance.accounts',
  'finance.expenseCategories',
  'finance.createAccount',
  'finance.updateAccount',
  'finance.transactions',
  'finance.createEntry',
  'finance.transfer',
  'finance.posTerminals',
  'finance.createPosTerminal',
  'finance.updatePosTerminal',
  'shopping.list',
  'shopping.requirements',
  'shopping.create',
  'payments.list',
  'payments.totals',
  'payments.create',
  'payments.changeStatus',
  'payments.refund',
  'reports.v15',
  'reports.customers',
  'customers.search',
  'customers.detail',
  'logs.server',
  'social.dashboard',
  'social.channels.list',
  'social.channels.save',
  'social.channels.test',
  'social.templates.list',
  'social.templates.save',
  'social.draft.generate',
  'social.preview',
  'social.posts.create',
  'social.posts.publish',
  'social.suggestions.list',
  'social.suggestions.dismiss',
  'social.automation.evaluate',
  'social.rules.list',
  'social.rules.save',
  'social.settings.get',
  'social.settings.save',
  'social.history',
  'social.targets.retry',
] as const

export type AdminOperation = typeof adminOperations[number]

export interface AdminOperationRequest {
  operation: AdminOperation
  payload?: unknown
}

export interface SecureConnectionConfiguration {
  databaseUrl: string
  cloudinary?: {
    cloudName: string
    apiKey: string
    apiSecret: string
  } | null
}

export interface ConnectionConfigurationStatus {
  configured: boolean
  source: 'environment' | 'encrypted' | 'missing'
  storageConfigured: boolean
}
